services:
  - type: web
    name: boxmagic-api
    runtime: node
    plan: starter
    region: oregon
    buildCommand: npm ci && npm run prisma:generate -w apps/api && npm run prisma:migrate:deploy -w apps/api && npm run build -w apps/api
    startCommand: node apps/api/dist/src/main.js
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: API_PORT
        value: 3001
      - key: WEB_ORIGIN
        value: https://agenda-1-inkp.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_SUCCESS_URL
        value: https://agenda-1-inkp.onrender.com/pay/success
      - key: STRIPE_CANCEL_URL
        value: https://agenda-1-inkp.onrender.com/pay/cancel

  - type: web
    name: boxmagic-web
    runtime: static
    buildCommand: npm ci && npm run build -w apps/web
    staticPublishPath: apps/web/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://boxmagic-api.onrender.com
